name: "BlockchainAPIs"
api-url: "https://api.blockchainapis.io"
package:
  name: blockchainapis
  author: Clarensia
  author-comment: |
    # Clarensia: https://www.clarensia.com is the company behind
    # the development of https://www.blockchainapis.io
  version: 0.1.1
  description: |
    The blockchain-apis package allow you to interact with Blockchain
    APIs in a synchronous and asynchronous way.

    If you are starting on a new project, it is better to use the async
    class, which is called: BlockchainAPIs

    If you already have a project and don't want to bother with async,
    you can use the BlockchainAPIsSync class.
  # The modules that you want to be exported when someone write from package import *
  all-exports: ["BlockchainAPIs"]
